//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilePathRoot
    {
        public long ID { get; set; }
        public string FullPath { get; set; }
        public string Type { get; set; }
        public Nullable<bool> AllowWrite { get; set; }
        public Nullable<bool> AllowRead { get; set; }
    }
}
