//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public long ID { get; set; }
        public long ProductID { get; set; }
        public long ImageStoreID { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ImageStore ImageStore { get; set; }
    }
}
