//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLine
    {
        public long ID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Condition { get; set; }
        public Nullable<long> SellerID { get; set; }
        public Nullable<decimal> OfferPrice { get; set; }
        public string TransactionType { get; set; }
        public bool Sold { get; set; }
        public Nullable<System.DateTime> SoldDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool Active { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
