//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipCode
    {
        public long ID { get; set; }
        public string Zipcode { get; set; }
        public string ZipCodeType { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string LocationType { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<double> Xaxis { get; set; }
        public Nullable<double> Yaxis { get; set; }
        public Nullable<double> Zaxis { get; set; }
        public string WorldRegion { get; set; }
        public string Country { get; set; }
        public string LocationText { get; set; }
        public string Location { get; set; }
        public Nullable<bool> Decommisioned { get; set; }
        public string TaxReturnsFiled { get; set; }
        public string EstimatedPopulation { get; set; }
        public string TotalWages { get; set; }
        public string Notes { get; set; }
    }
}
